spring.application.name=vaccination-service

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/vaccine?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Mysql@ppj6803
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
server.port=8082

user.service.url=http://localhost:8081

# looging
logging.level.com.cvn.vaccination.client=DEBUG
logging.level.feign=DEBUG

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest