spring.application.name=user-service

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/cvn?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Mysql@ppj6803
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
server.port=8081

# JWT Configuration
# secret key --- 256 bits -- 64 characters -- standard for HS256
jwt.secret.key=1c6dc9629fec451754d5e890d32e79adebb28a45ac71b8bc80c8852c1fb32de6
# access-token expiry -- 15 min and refresh-token expiry -- 7 days
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest